apiVersion: apps/v1
kind: Deployment
metadata:
  name: hami0825
  namespace: haenu
spec:
  selector:
    matchLabels:
      app: hami0825
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: hami0825
    spec:
      containers:
      - name: hami0825
        image: 597014485214.dkr.ecr.ap-northeast-2.amazonaws.com/hami0825:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 128Mi
        env:
        - name: PY_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: PY_ENVIRONMENT
        - name: CHANNEL
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: CHANNEL
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: USER_ID
        - name: APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: APP_TOKEN
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: DB_HOSTNAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: DB_DATABASE
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: hami0825
              key: DB_PORT
